### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by fnaith** [andyli/HaxeCI#6]
AFAIK, the most frustrating part of CI is inconsistent behavior between environments.

And thanks for maintaining the project that helps other protects CI flow.

Could you mind adding version number to note current commit is stable or under testing ?

**Comment by andyli** [comment]
This is more of an example project instead of a library. As long as the build badges are green, it is good.
I totally share your dream of having a stable, version-pinned CI env, but sadly, neither TravisCI and AppVeyor has proper versioning so there is not much HaxeCI can do as a downstream project. All I can do is to play catch up constantly.

**Comment by fnaith** [comment]
Ha, understandable.
Still appreciate this work.
